name: Docker Image CI
on: [ push, create ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pandoc: [ 2.19, 3.0.1, 3.1 edge-alpine ]
        alpine: [ 3.16.4 ]
        variant: [ latex ]
        tlmgr: [ false true ]
        include:
          - pandoc: 2.16
            alpine: 3.12
            variant: latex
            tlmgr: true
          - pandoc: 2.17
            alpine: 3.14
            variant: latex
            tlmgr: true
          - pandoc: 2.18
            alpine: 3.14
            variant: latex
            tlmgr: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            ubuntu_version=22.04
            nexe_version=4.0.0-beta.19
            alpine_version=${{matrix.alpine}}
            pandoc_version=${{matrix.pandoc}}
            pandoc_variant=${{matrix.variant}}
            tlmgr=${{matrix.tlmgr}}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pandocker-alpine:${{matrix.pandoc}}
