name: Docker Image CI
on: [ push, create ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pandoc: [ 2.19 ]
        alpine: [ 3.16.4 ]
        variant: [ latex ]
        tlmgr: [ true ]
        texlive: [ 2022 ]
        lua: [ 5.3 ]
        pip_opt: [ "" ]
        include:
          - pandoc: 3.1
            alpine: 3.16.4
            variant: latex
            tlmgr: true
            texlive: 2022
            lua: 5.4
          - pandoc: 3.2.0
            alpine: edge
            variant: latex
            tlmgr: false
            texlive: 2023
            lua: 5.4
          - pandoc: 3.1.1
            alpine: 3.16.4
            variant: latex
            tlmgr: true
            texlive: 2022
            lua: 5.4
          - pandoc: edge-alpine
            alpine: edge
            variant: latex
            tlmgr: false
            texlive: 2023
            lua: 5.4
            pip_opt: "--break-system-packages"
          - pandoc: 2.16
            alpine: 3.12
            variant: latex
            tlmgr: true
            texlive: 2021
            lua: 5.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout pandoc-misc
        uses: actions/checkout@v3
        with:
          ref: 2.16.2
          repository: k4zuki/pandoc_misc
          path: src/pandoc_misc
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            ubuntu_version=22.04
            nexe_version=4.0.0-beta.19
            alpine_version=${{matrix.alpine}}
            pandoc_version=${{matrix.pandoc}}
            pandoc_variant=${{matrix.variant}}
            lua_version=${{matrix.lua}}
            tlmgr=${{matrix.tlmgr}}
            texlive=${{matrix.texlive}}
            pip_opt=${{matrix.pip_opt}}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pandocker-alpine:${{matrix.pandoc}}
