#| pandoc   | tags                          | Alpine | Ubuntu | TeXLive | Lua |
#|----------+-------------------------------+--------+--------+---------+-----|
#| main     | edge                          | 3.21.0 | noble  |         |
#| 3.6.1    | 3.6.1.0  3.6.1  3.6  3 latest | 3.21.0 | noble  |    2024 |
#| 3.5      | 3.5.0.0  3.5.0  3.5           | 3.20.3 | noble  |    2024 |
#| 3.4      | 3.4.0.0  3.4.0  3.4           | 3.20.3 | noble  |    2024 |
#| 3.3      | 3.3.0.0  3.3.0  3.3           | 3.20.3 | noble  |    2024 |
#| 3.2.1    | 3.2.1.0  3.2.1  3.2           | 3.19.4 | noble  |    2024 |
#| 3.1.13   | 3.1.13.0 3.1.13 3.1           | 3.19.1 | noble  |    2024 | 5.4 |
#| 3.1.1    | 3.1.1.0  3.1.1                | 3.16.8 | jammy  |    2022 | 5.4 |
#| 3.0.1    | 3.0.1.0  3.0.1  3.0           | 3.16.8 | jammy  |    2022 | 5.4 |
#| 2.19.2   | 2.19.2.0 2.19.2 2.19 2        | 3.16.8 | jammy  |    2022 | 5.3 |

name: Docker Image CI
on:
  workflow_dispatch:
  push:
  create:
  schedule:
    - cron: '0 15 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pandoc: [ 2.19 ] # pandoc version
        alpine: [ 3.16.8 ] # OS version
        variant: [ latex, core ] # pandoc image variant
        tlmgr: [ true ] # `true`: use frozen/outdated TeXLive version and its package server; false: use pre-installed version
        texlive: [ 2022 ] # TeXLive version
        lua: [ 5.3 ] # lua version
        pip_opt: [ "" ] # pip option on non-OS controlled packages install
        rsvg_convert: [ "" ]
        include:
          - pandoc: "3.1"
            alpine: 3.19.1
            variant: latex
            tlmgr: false
            texlive: 2024
            lua: 5.4
            pip_opt: "--break-system-packages"
            rsvg_convert: rsvg-convert
          - pandoc: "3.2"
            alpine: 3.19.1
            variant: latex
            tlmgr: false
            texlive: 2024
            lua: 5.4
            pip_opt: "--break-system-packages"
            rsvg_convert: rsvg-convert
          - pandoc: "edge-alpine"
            alpine: 3.21.0
            variant: latex
            tlmgr: false
            texlive: 2024
            lua: 5.4
            pip_opt: "--break-system-packages"
            rsvg_convert: rsvg-convert
          - pandoc: "3.2"
            alpine: 3.19.1
            variant: core
            tlmgr: false
            texlive: 2024
            lua: 5.4
            pip_opt: "--break-system-packages"
            rsvg_convert: rsvg-convert
          - pandoc: "3.5"
            alpine: 3.20.3
            variant: core
            tlmgr: false
            texlive: 2024
            lua: 5.4
            pip_opt: "--break-system-packages"
            rsvg_convert: rsvg-convert
          - pandoc: "3.6"
            alpine: 3.21.0
            variant: core
            tlmgr: false
            texlive: 2024
            lua: 5.4
            pip_opt: "--break-system-packages"
            rsvg_convert: rsvg-convert

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Checkout pandoc-misc
        uses: actions/checkout@v3
        with:
          ref: 2.16.2
          repository: k4zuki/pandoc_misc
          path: src/pandoc_misc
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            ubuntu_version=22.04
            nexe_version=4.0.0-rc.6
            alpine_version=${{matrix.alpine}}
            pandoc_version=${{matrix.pandoc}}
            pandoc_variant=${{matrix.variant}}
            lua_version=${{matrix.lua}}
            tlmgr=${{matrix.tlmgr}}
            texlive=${{matrix.texlive}}
            pip_opt=${{matrix.pip_opt}}
            rsvg_convert=${{matrix.rsvg_convert}}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pandocker-alpine:${{matrix.pandoc}}-${{matrix.variant}}
